### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] avec cartiflette.s3.download_vectorfile_url_all

### ISSUE THREAD

**Issue by AsdaeSunspark** [InseeFrLab/cartiflette#46]
Bonjour. Je rencontre un problème avec le certificat SSL lorsque j'essaie d'utiliser `cartiflette.s3.download_vectorfile_url_all` :
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>`

Je travaille sur l'application Microsoft Visual Studio. Je ne comprends pas ce qui se passe dans le détail, mais de ce que je vois SSL est un protocole de sécurité que Python gère à travers le module SSL. Il a besoin d'un certificat géré par le module `certifi`.

Le problème ne vient pas de `certifi`, il est bien à jour, j'ai désinstallé et réinstallé le module et ai même essayé une version plus ancienne, sans succès.

L'erreur a l'air courante à en croire StackOverflow (avec d'autres fonctions que celles de `cartiflette`), la solution la plus courante est :

```
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```

Cependant cela revient à désactiver un protocole de sécurité, aussi ne suis-je pas sûr que c'est une idée à suivre ...

Merci du suivi!

**Comment by linogaliana** [comment]
Le problème n'a plus l'air d'exister, il devait être temporaire. Je ferme l'issue
