### ISSUE TITLE
Etapes de validation des données avant production fonds cartiflette

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/cartiflette#52]
L'idée exprimée par @cedricr sur Tchap cette semaine me paraît importante pour fiabiliser `cartiflette` :

> "on pourrait peut-être réflechir à avoir une phase de nettoyage des données avant de les servir (ne serait-ce qu'un simple st_makevalid ou un buffer(0)…)"

**Comment by tgrandje** [comment]
@linogaliana @cedricr 
J'ai glissé une fonction de nettoyage des géométries, mais directement à l'issue du téléchargement plutôt qu'à l 'intérieur de `duplicate_vectorfile_ign`. Si j'ai bien compris les fonctions du module download pourraient aussi servir en propre (en dehors du sujet de restructuration des données), donc ça m'a paru plus naturel*. On peut bien sûr bouger ça...

* _notamment j'ai vu que tu avais mis en place un système de cache et aperçu quelques commentaires sur le md5, mais aucun contrôle de signature (il me semble). Si jamais j'ai raté quelque chose (ou si on décide d'ajouter ce type de contrôle), on gagnerait sans doute en lisibilité à tout mettre validation & contrôle signature au même emplacement...? _ 


(Au passage, j'ai un (petit) sujet de discussion sur les mérites comparés de buffer vs. make_valid)

**Comment by linogaliana** [comment]
- @tgrandje Il me semble que #72 règle ceci, je ferme. Si tu penses que c'est toujours d'actualité, tu peux ouvrir à nouveau
