### ISSUE TITLE
Optimisation des téléchargements (md5)

### ISSUE THREAD

**Issue by tgrandje** [InseeFrLab/cartiflette#55]
Ajouter un contrôle du md5 avant de lancer un téléchargement

**Comment by tgrandje** [comment]
```
r = requests.Session()
url = "https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS_SHP_TERRITOIRES_PACK_2023-02-16$ADMIN-EXPRESS_3-1__SHP_LAMB93_FXX_2023-02-16/file/ADMIN-EXPRESS_3-1__SHP_LAMB93_FXX_2023-02-16.7z"
r = s.get(url, stream=True)
print(r.headers['content-md5'])
```

**Comment by linogaliana** [comment]
ça semble prometteur:

```python
import os
from cartiflette.download import create_url_adminexpress, get_vectorfile_ign


url = create_url_adminexpress(
        provider="IGN", year=2022, source="EXPRESS-COG-TERRITOIRE", field="reunion"
    )

import requests
r = requests.Session()
r = r.get(url, stream=True)
md5 = r.headers['content-md5']

get_vectorfile_ign(
    provider="IGN", year=2022, source="EXPRESS-COG-TERRITOIRE", field="reunion"
)

filename = [path for path in os.listdir("/tmp") if path.endswith(".7z")]

hashlib.md5(open(f"/tmp/{filename[0]}",'rb').read()).hexdigest() == r.headers['content-md5'] #True
```

**Comment by tgrandje** [comment]
@linogaliana Oui, j'ai commencé à regarder comment intégrer ça.
Par contre, il me semble (de mémoire) qu'en l'état actuel, ton téléchargement se fait en local (tempfile) dans une fonction qui n'a pas accès au chemin du s3 -> il faut sans doute réécrire les fonctions avec ça à l'esprit pour éviter un téléchargement si on peut checker le md5 directement (et aussi de manière harmonisée avec un éventuel accès via l'API géoportail et/ou le FTP, qui n'ont pas accès au md5 de la même manière). Je te tiens au courant.

**Comment by tgrandje** [comment]
@linogaliana 
Je viens de contrôler ce que j'avais commencé à analyser :

- le plus "simple" me semble de réécrire les fonctions de téléchargement dès le niveau dev.download_store_admin_express (a priori, pas appelée ailleurs dans le code). Parmi les fonctions "filles" appelées ailleurs, j'ai un doute sur "download_write" qui est utilisée aussi dans get_BV. Peux-tu me confirmer qu'on est bien sur une fonction provisoire jamais finalisée à ce stade, et qu'on peut se permettre de "casser" provisoirement la chaîne ?
- je pense qu'avec le roulement des providers, il faut prévoir quelque chose de plus complexe pour stocker les md5 ; à ce stade, on ne peut pas exclure que les md5 soient différents entre un provider et l'autre. Notamment, le md5 du requests.header est un md5 de la requête, pas d'une couche individuelle à l'intérieur de l'archive téléchargée (laquelle contient un fichier md5 détaillé si je me souviens bien). A l'inverse, si on attaque l'API géoportail, le md5 n'est pas disponible avant téléchargement (un sujet à évoquer avec l'IGN ?) et on va donc hasher la couche seule. Du coup, j'imagine plutôt un json centralisé à la racine du s3, peut-être un truc qui référence les deux niveaux de md5 (http response header & couche) et pour chaque provider. Maintenant, comment on pourra détecter quel fichier est le "plus" à jour parmi les différents candidats en provenance des différents providers, je n'en ai aucune idée...

**Comment by linogaliana** [comment]
@tgrandje , il me semble qu'on est bon maintenant sur cette _issue_, on peut la fermer ?

**Comment by linogaliana** [comment]
@tgrandje je ferme, tu ré-ouvres si tu as un état d'âme
