### ISSUE TITLE
Enrichir ADMIN-EXPRESS-COG d'informations qualitatives

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/cartiflette#7]
J'ai noté qu'AdminExpress-COG, qui est bien pratique, ne comporte néanmoins pas les noms de régions et de département. Il faudra quand même apparier au COG pour les avoir. Ce sont en effet des critères de sélection intéressants pour un utilisateur de données géographiques (perso je connais pas le code région d'Occitanie)

**Comment by hadrilec** [comment]
Salut,

avec l'[api metadata](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=M%C3%A9tadonn%C3%A9es&version=V1&provider=insee) de l'insee des listes peuvent etre recuperees.

Sinon avec `pynsee`, les noms de communes sont fournis avec ceux des departements et des regions :

```
from pynsee.localdata.get_geo_list import get_geo_list
city_list = get_geo_list('communes')
region_list = get_geo_list('regions')
departement_list = get_geo_list('departements')
arrondiss_list = get_geo_list('arrondissements')
```

**Comment by linogaliana** [comment]
Merci @hadrilec des infos. Je regarderai ça quand j'aurais le temps
